    version: '3.8'

    services:
      chatbot-frontend:
        build: .
        container_name: chatbot-contable-frontend-prod
        # Mapea el puerto 3001 del servidor al puerto 3000 del contenedor
        ports:
          - "3001:3000"
        # Carga las variables de entorno desde el archivo de producción
        env_file:
          - .env.production
        # Siempre reinicia el contenedor a menos que lo detengas manualmente
        restart: unless-stopped
    

